#!/bin/bash

echo
echo "########################################################"
echo "####         Uninstall Docker & Dependencies        ####"
echo "########################################################"
echo

echo
# Uninstall Virtualbox
if [ -x "$(command -v virtualbox)" ]; then
	echo "Virtualbox found, uninstalling..."
	brew cask uninstall --force virtualbox
else
	echo "Virtualbox not found, already uninstalled..."
fi

echo
# Uninstall Docker Toolbox ( docker, docker-compose, docker-machine, docker-machine-parallels )
if [ -x "$(command -v docker)" ]; then
	echo "Docker Toolbox found, uninstalling..."
	brew uninstall --force docker-machine-parallels
	brew uninstall --force docker docker-compose docker-machine
else
	echo "Docker Toolbox not found, already uninstalled..."
fi

echo
# Uninstall Watchman
if [ -x "$(command -v watchman)" ]; then
	echo "Watchman found, uninstalling..."
	brew uninstall --force watchman
else
	echo "Watchman not found, already uninstalled..."
fi

echo
# Uninstall FSwatch
if [ -x "$(command -v fswatch)" ]; then
	echo "FS Watch found, uninstalling..."
	brew uninstall --force fswatch
else
	echo "FS Watch not found, already uninstalled..."
fi

echo
# Uninstall Core Utilities
if [ -x "$(command -v greadlink)" ]; then
	echo "GNU core utilities found, uninstalling..."
	brew uninstall --force coreutils
	brew uninstall --force gnu-sed
else
	echo "GNU core utilities not found, already uninstalled..."
fi
