#!/bin/bash

# Docker scripts variables

openvpn_data="openvpn_data"

aws_account_id="xxxxxxxxxx"

application_name="platform"

machine_name="${application_name}-dev"

vpn_url="vpn.${application_name}.local.com"

deploy_machine_name="${machine_name}-deploy"

repository_url="${aws_account_id}.dkr.ecr.us-east-1.amazonaws.com"
