#!/bin/bash

echo
echo "########################################################"
echo "####           Run Docker Database Command          ####"
echo "########################################################"
echo

source docker/vars

source docker/banner

echo
echo "Start Machine..."
docker-machine start $machine_name

echo
echo "Attach Machine to Terminal..."
eval $(docker-machine env --shell bash $machine_name)

echo
echo "Run Database Command..."
docker exec -it ${application_name}_database_1 psql -U "postgres" -d "${application_name}" $@
