#!/bin/bash

echo
echo "########################################################"
echo "####             Build Deployment Images            ####"
echo "########################################################"
echo

source docker/vars

echo
echo "Build Docker Images..."
docker-compose -p $application_name -f docker-compose/prod.yml build --pull
docker-compose -p $application_name -f docker-compose/jenkins.yml build --pull
