#!/bin/bash

echo
echo "########################################################"
echo "####        Clean Docker Images/Containers          ####"
echo "########################################################"
echo

full=$1

source docker/vars

echo
echo "Start Machine..."
docker-machine start $machine_name

echo "Attach Machine to Terminal..."
eval $(docker-machine env --shell bash $machine_name)

# Remove all lingering containers not in use
echo "Remove Lingering Containers..."
docker rm -f $(docker ps -aqf status=dead)
docker rm -f $(docker ps -aqf status=exited)

# Remove all volumes that are exited
echo "Remove Exited Volumes..."
docker rm -v $(docker ps -aqf status=dead)
docker rm -v $(docker ps -aqf status=exited)

# Remove all intermediary images
echo "Remove Dangling images..."
docker rmi -f $(docker images -aqf "dangling=true")

# Remove everything
if [ "$full" = "full" ]; then
	echo "Remove All Containers..."
	docker rm -f $(docker ps -aq)

	echo "Remove All Volumes"
	docker rm -v $(docker ps -aq)

	echo "Remove All Images"
	docker rmi -f $(docker images -aq)

	echo "Remove Dangling volumes"
	docker volume rm $(docker volume ls -qf "dangling=true")
fi

echo
echo "!!! DOCKER CLEANED !!!"
echo
