#!/bin/bash

echo
echo "########################################################"
echo "####       Enter Docker Deploy Environment          ####"
echo "########################################################"
echo

source docker/vars

source docker/banner

source docker/deploy/pre-compose

echo
echo "Entering Deployment Bash Terminal..."
sh docker/deploy/run "bash"
