#!/bin/bash

echo
echo "########################################################"
echo "####        Rebuild Docker Deploy Environment       ####"
echo "########################################################"
echo

source docker/vars

echo
echo "Destroy Old Machine..."
source docker/deploy/destroy

echo
echo "Setup New Machine..."
source docker/deploy/setup