#!/bin/bash

echo
echo "########################################################"
echo "####          Elastic Beanstalk SSH Server          ####"
echo "########################################################"
echo

source docker/deploy/vars

source docker/deploy/banner

source docker/deploy/pre-compose

sh docker/deploy/run "eb ssh $@"
