#!/bin/bash

echo
echo "########################################################"
echo "####         Start Docker Deploy Environment        ####"
echo "########################################################"
echo

app=$1

if [ -z "$app" ]; then
	app="deploy";
fi

source docker/deploy/vars

source docker/deploy/banner

source docker/deploy/pre-compose

source docker/deploy/compose $app

source docker/deploy/init
