#!/bin/bash

# Docker deploy scripts variables

openvpn_data="openvpn_data"

aws_account_id="xxxxxxxxxxxx"

application_name="platform"

vpn_url="vpn.$application_name.co.uk"

machine_name="$application_name-dev-deploy"

repository_url="$aws_account_id.dkr.ecr.us-east-1.amazonaws.com"
