#!/bin/bash

# Docker deploy details variables

# Retrieve from command line
version=$1
description=$2
deploy_target=$3
application_type=$4
application_name="platform"

unix_timestamp="$(date +%s)"
gitignore_path="$PWD/.gitignore"
deployment_branch="deployment-$unix_timestamp"
timestamp="$(date +'%d-%m-%Y')-$(date +'%H.%M.%S')"

current_branch="$(git symbolic-ref --short -q HEAD)"
types=("dev" "prod" "intranet" "website" "jenkins" "api")
targets=("${application_name}-development" "${application_name}-testing" "${application_name}-intranet" "${application_name}-api" "${application_name}-jenkins")
